### ISSUE TITLE
建议 消息发布允许新增多发布模板

### ISSUE THREAD

**Issue by yuelwish** [ptma/mqtt-insight#11]
版本 1.0.0
系统 arch linux

场景:
  当你在调试某些设备或命令时, 你会有多个候选指令, 比如 我调试 物联网设备的时候 会有 分闸指令  合闸指令, 只有一个输入框, 我就得专门找一个技术本, 记录 合闸是什么topic payload 分闸是什么topic payload 非常的麻烦

期望:
1. 有一个类似这样的 tab:   [分闸] [合闸]  [读取] + 
可以直接让我去选择我预设的消息模板, 我自己去重命名记录, 另外我这里的指令可能不一定是json 也可能是 hex 所以 每个 tab的消息编码也可以是不一样的

2. 提供类似于 {{uuid}}  {{timestamp}} {{rand}} 类似这种系统变量 直接替换topic 或  payload 中的内容

**Comment by ptma** [comment]
你可以使用脚本功能。

如果你要手动发送，其实也可以， 手动发送简单的指令消息（比如1、2、3...）到空闲的主题，脚本里可以使用 codec.decode([String topic], callback) 获取这个主题的消息， 然后再根据指令组装实际的指令消息并发送。

**Comment by yuelwish** [comment]
还是易用性的问题,  写脚本, 虽然我也是程序员, 但是我依然有需要学习这个脚本的学习成本, 调试成本

如果是直接的图形化, 直接放上去就可以了, 不管是不是程序员都可以直接使用.

并且就拿这个功能做消息备忘也不错啊, 并且我修改起来也非常方便
