### ISSUE TITLE
bug 预览区域的格式化不起作用

### ISSUE THREAD

**Issue by yuelwish** [ptma/mqtt-insight#13]
版本 1.0.0

现状
     订阅格式为 plain ,
     更多 消息格式为 json, 预览勾选格式化
     预览区域 格式化 无效
     
疑惑:
 我理解的更多的消息格式应该是所谓全局的消息解码模式, 但是全局模式我没有发现 atuo ??
 订阅区域的解码, 应该是当前消息自定义的解码模式,也就是跟全局不一样的解码模式

期望:
    预览区域的格式化能在当前消息的解码模式下, 再次识别做格式化 比如 base64之后 是个json 再格式化
    并且预览区域的解码可以再次修改, 比如 我是按plain做的解码, 实际上这个应该是2禁止, 所以我向重新单独看看这个消息的hex的内容

**Comment by ptma** [comment]
更多里面的消息格式是实例下全局的格式，具体订阅的格式为auto的，才采用全局格式。

消息格式隶属于订阅，格式化时也是按这个逻辑判断具体格式。

你这种情况，订阅时还是要细化，不要通配订阅。
很难想象同一主题下的消息格式不一致这种场景。

**Comment by yuelwish** [comment]
预览一般只会看一条消息, 所以这里的格式化我认为只需要看当前消息就可以了.

或者这样讲, 我不明白为啥预览这里还需要存在一次格式化的选项,

假设不存在格式化选项,
我全局选的json,  并且我订阅也是 auto  那么在消息列表,展示出来就应该是格式化后的json

反过来, 如果存在格式化的选项, 那不就意味着, 这里可以再一次按照选定的格式来格式化一次
