### ISSUE TITLE
建议 已订阅内容允许再次编辑

### ISSUE THREAD

**Issue by yuelwish** [ptma/mqtt-insight#2]
版本 1.0.0

建议 已订阅内容允许再次编辑

**Comment by ptma** [comment]
你的意思是编辑订阅的主题？

如果是这样，你可以取消订阅（可关闭，也可保留这个订阅列表），再新增一个订阅。

**Comment by yuelwish** [comment]
右键 --- 编辑 -- 确定 3步
现在是 指定位置 -- 选择关闭  -- 新建 -- 写新的topic -- 确定  最起码5步

其中还有 现在还没法复制原有的 topic 的问题, 关闭之后会导致原有的消息全部消失的问题

图形好工具就是为了方便, 能简化步骤就简化步骤
