### ISSUE TITLE
建议 已经订阅内容支持右键菜单

### ISSUE THREAD

**Issue by yuelwish** [ptma/mqtt-insight#3]
版本 1.0.0

已经订阅内容支持右键菜单
提供最常见的操作:
     禁用/启用
     编辑
     消息格式

**Comment by ptma** [comment]
1、禁用启用不就是订阅和取消订阅？
2、同 #1
3、已有

**Comment by yuelwish** [comment]
功能是有, 一个订阅菜单哪里都能右键, 现在的是必须指向指定的位置单击 再选择, 这是一个快捷程度的问题

就像是桌面你随意右键 刷新  跟浏览器 对比 必须是指定位置刷新, 哪个更方便

并且这里的取消 和 关闭, 我现在操作都是当前 订阅直接从订阅列表消失了,  我猜测这是bug.  但是你又有一个叫做订阅(保留列表)这让我非常的困惑

这里应该是 禁用订阅 /  重新订阅   /  删除 才对

这里我的都是图形化的操作方便, 而不是说这个功能有,  这样  这样 就能找到, 我觉得这是用户体验的问题

**Comment by ptma** [comment]
可能确实是 “取消订阅 / 重新订阅 / 关闭” 比较好。

**Comment by ptma** [comment]
可能确实是 “取消订阅 / 重新订阅 / 关闭” 比较好。

**Comment by yuelwish** [comment]
关闭也存在歧义, 直接删除 或者 销毁
