### ISSUE TITLE
bug 无法保存历史订阅内容

### ISSUE THREAD

**Issue by yuelwish** [ptma/mqtt-insight#5]
版本 1.0.0
系统: arch linux

现状:
当我进行订阅之后,  不管我是收藏了, 还是没有收藏, 关闭软件后, 再次打开重联后, 订阅列表都是空的

期望:
1. 订阅之后, 无论是否收藏, 软件重启中后,都应该将订阅还原到订阅列表
2. 并且能保持一定数量的之前订阅的历史消息

另外: 收藏我没发现这个到底有什么用, 建议去掉

**Comment by ptma** [comment]
关闭再打开，连接管理里连接还在吗？
Linux下我无法测试，请补充细节。

**Comment by yuelwish** [comment]
连接都在,  我也去 ~/MqttInsight/conf/config.json 里面去看了, 我猜你 favoriteSubscriptions 是用来保存历史订阅的, 但是我这里是空的  "favoriteSubscriptions": []
