### ISSUE TITLE
bug 订阅消息展示为乱码

### ISSUE THREAD

**Issue by yuelwish** [ptma/mqtt-insight#6]
版本 1.0.0
系统 arch linux

描述:
订阅主题 消息格式为 auto
当我发送二进制消息时, 消息为乱码

期望:
当消息为不可见字符时, 能够自动使用hex的方式进行展示
或者 
能否提供一个 atuo + 被选解码 这种形式

**Comment by ptma** [comment]
连接管理里没个连接可以设置默认消息格式，默认为plain，添加订阅时，如果选auto，就是采用连接的默认格式。每个订阅只能是一种格式。

如果你要区分，添加订阅的时候按主题细化，不要通配订阅。

发布消息时需要选择格式。

**Comment by yuelwish** [comment]
这里, 其实我认为的应该是你的命名存在问题, 如果 更多解码格式那里为 plain , 那么订阅那里应该默认也为 plain ,而不是 auto,  auto 只会让人理解为自动解码, 而不是自动使用全局解码方式. 这里的auto容易造成误解

另外我们还真有 同一个topic 又给 二进制 又给 json的方式, 透传网关, 网关自身信息给的是json 但是透传上来的内容就是二进制, 而且topic还是不变的, 这类设备应该都会是这种样子. 所以我才会有这种被选解码方案的需求.
