### ISSUE TITLE
建议 消息发布按钮移动到右下角

### ISSUE THREAD

**Issue by yuelwish** [ptma/mqtt-insight#9]
版本 1.0.0

消息发布按钮, 目前在左下角

期望:
   建议移动到右下角,  没啥原因只是感觉非常的别扭, 我们已经被 各大聊天软件教育的非常成功了,
   发送按钮放到左边感觉比较反人类.

**Comment by ptma** [comment]
Ctrl + Enter

**Comment by yuelwish** [comment]
还是那句话, 这是易用性的问题, 如果操作mqtt的发布, 一定不是为了像聊天那样, 求快, 反而而是不敢随意发的, 发布求稳定, 确认了才能发.
